align_images: !!python/tuple
- 4
- 16
create_downsampled_mask: 16
create_full_resolution_mask: 4
create_neuroglancer: !!python/tuple
- 4
- 16
create_web_friendly_image: 4
create_within_stack_transformations: 4
extract_tifs_from_czi: 4
make_histogram: 16
name: ratto
parallel_create_cleaned: !!python/tuple
- 4
- 16
extract_slide_meta_data_and_insert_to_database: 15