align_images: !!python/tuple
- 4
- 5
create_downsampled_mask: 12
create_full_resolution_mask: 4
create_neuroglancer: !!python/tuple
- 4
- 16
create_web_friendly_image: 4
create_within_stack_transformations: 4
extract_tifs_from_czi: 4
make_histogram: 12
name: basalis
parallel_create_cleaned: !!python/tuple
- 4
- 12
prepare_image_for_quality_control: 4
